seed = 1
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-1-credit"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0002864413699806913
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 816
dropout = 0.0
