seed = 7
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-0-pol"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0007174123972972572
weight_decay = 0.0010428387942827905

[model]
arch_type = "tabm"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 768
dropout = 0.15042214777905838

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 12

[bins]
n_bins = 32
