seed = 10
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-2-MiamiHousing2016"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0012321815715832002
weight_decay = 0.00018203341045080898

[model]
arch_type = "tabm-mini"
k = 32
share_training_batches = false

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 928
dropout = 0.14571322900458689

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 8

[bins]
n_bins = 21
