seed = 12
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-0-MiamiHousing2016"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.000418422613391385
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 256
dropout = 0.05954705110287806
