seed = 0
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-1-fifa"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 8.572543983761397e-05
weight_decay = 0.0003415118977231612

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 608
dropout = 0.39187438036539224

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 16

[bins]
n_bins = 111
