seed = 8
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-1-Ailerons"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0022217248247845796
weight_decay = 0.059895547222137094

[model]
arch_type = "tabm-mini"
k = 32
share_training_batches = false

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 528
dropout = 0.16232123712081217

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 20

[bins]
n_bins = 21
