seed = 13
batch_size = 128
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-0-cpu_act"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.003124845927837436
weight_decay = 0.022958165846894838

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 480
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 16

[bins]
n_bins = 91
