seed = 8
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/cooking-time"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 4.130283538426954e-05
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 112
dropout = 0.17634234295991302
