seed = 7
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-0-Mercedes_Benz_Greener_Manufacturing"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.00010586734570340832
weight_decay = 0.0001712949991561048

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 5
d_block = 944
dropout = 0.17895457879968157
