seed = 4
batch_size = 128
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-2-isolet"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.001864385017250235
weight_decay = 0.00011031187969490146

[model]
arch_type = "tabm"
k = 32
share_training_batches = false

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 912
dropout = 0.12239672999459525

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 12

[bins]
n_bins = 35
