seed = 14
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-2-kdd_ipums_la_97-small"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 5.149505482356892e-05
weight_decay = 0.041200559803580325

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 832
dropout = 0.24386420962165373

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 20

[bins]
n_bins = 24
