seed = 12
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/microsoft"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 3.5561744969003275e-05
weight_decay = 0.037414078721369634

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 736
dropout = 0.47004815801361105

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 8

[bins]
n_bins = 15
