seed = 10
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-0-Ailerons"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 8.474359176397792e-05
weight_decay = 0.0017489966737814604

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 736
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 20

[bins]
n_bins = 13
