seed = 4
batch_size = 32
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-1-wine"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0005487863409787782
weight_decay = 0.0

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 640
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 16

[bins]
n_bins = 83
