seed = 8
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-1-Brazilian_houses"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0001058298535803232
weight_decay = 0.0001515920461138471

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 5
d_block = 704
dropout = 0.0
