seed = 10
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-0-fifa"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0005393490313533756
weight_decay = 0.09094448176985837

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 1024
dropout = 0.21206687236640734

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 8

[bins]
n_bins = 101
