seed = 13
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-1-kdd_ipums_la_97-small"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0016905162371832398
weight_decay = 0.0

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 176
dropout = 0.47238121141028844

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 32

[bins]
n_bins = 65
