seed = 14
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-1-pol"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0006594375075483318
weight_decay = 0.09686973613580671

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 880
dropout = 0.0
