seed = 9
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/weather"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0006717314756003656
weight_decay = 0.09790142556734852

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 496
dropout = 0.25153797241328196
