seed = 5
batch_size = 32
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-3-wine"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.001336468030052141
weight_decay = 0.0001942919073540181

[model]
arch_type = "tabm"
k = 32
share_training_batches = false

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 944
dropout = 0.1636151035995557

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 8

[bins]
n_bins = 8
