seed = 14
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-3-analcatdata_supreme"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00029774215065104674
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 880
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 8

[bins]
n_bins = 124
