seed = 9
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-0-elevators"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0010527098390228236
weight_decay = 0.021083269999705622

[model]
arch_type = "tabm"
k = 32
share_training_batches = false

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 912
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 8

[bins]
n_bins = 88
