seed = 5
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-0-analcatdata_supreme"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00013856444206374638
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 96
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 24

[bins]
n_bins = 19
