seed = 3
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/churn"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0014215026863743632
weight_decay = 0.0

[model]
arch_type = "tabm"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 656
dropout = 0.49476959904460954

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 28

[bins]
n_bins = 37
