seed = 13
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-2-analcatdata_supreme"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0010054631923436892
weight_decay = 0.0005948571267693014

[model]
arch_type = "tabm-mini"
k = 32
share_training_batches = false

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 976
dropout = 0.04724032121308054

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 28

[bins]
n_bins = 95
