seed = 5
batch_size = 32
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-2-wine"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00098596951558785
weight_decay = 0.0002775663609756555

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 5
d_block = 272
dropout = 0.0
