seed = 8
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/maps-routing"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0007956065233413322
weight_decay = 0.04866707051084182

[model]
arch_type = "tabm"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 400
dropout = 0.23823558569097308

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 8

[bins]
n_bins = 2
