seed = 3
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-0-MagicTelescope"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.001967509978800041
weight_decay = 0.02710751787348629

[model]
arch_type = "tabm"
k = 32
share_training_batches = false

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 448
dropout = 0.41810371642750277

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 12

[bins]
n_bins = 7
