seed = 3
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/ecom-offers"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00012923707060273325
weight_decay = 0.00040732699269455027

[model]
arch_type = "tabm-mini"
k = 32
share_training_batches = false

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 848
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 8

[bins]
n_bins = 72
