seed = 6
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/sberbank-housing"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0008363771605209775
weight_decay = 0.00020122942475059552

[model]
arch_type = "tabm-mini"
k = 32
share_training_batches = false

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 528
dropout = 0.3143893463355451

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 32

[bins]
n_bins = 73
