seed = 13
batch_size = 128
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-0-wine_quality"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0008225376469549832
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 5
d_block = 432
dropout = 0.06091260982520949
