seed = 3
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-0-bank-marketing"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0006427846523970299
weight_decay = 0.0933058311262204

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 6
d_block = 656
dropout = 0.36821544920295657
