seed = 14
batch_size = 32
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-4-wine"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00011636139679712915
weight_decay = 0.0005589856833062862

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 5
d_block = 672
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 8

[bins]
n_bins = 44
