seed = 11
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/delivery-eta"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0012566701454869743
weight_decay = 0.009521109846831296

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 288
dropout = 0.03703833959818663

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 28

[bins]
n_bins = 113
