seed = 1
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-1-MiamiHousing2016"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0006165886667534534
weight_decay = 0.005140350928811011

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 752
dropout = 0.2262076843608539

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 20

[bins]
n_bins = 60
