seed = 13
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-0-kdd_ipums_la_97-small"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0015428676101909631
weight_decay = 0.0

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 464
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 24

[bins]
n_bins = 45
