seed = 13
batch_size = 128
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-0-wine_quality"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0009291627877187181
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 816
dropout = 0.44713868508520105

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 60
d_embedding = 32
frequency_init_scale = 0.4279702298907353
lite = false
