seed = 11
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-1-fifa"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0007428158624746786
weight_decay = 0.0027078470644655646

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 5
d_block = 1024
dropout = 0.1924331905986025
