seed = 4
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-0-credit"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00010362921497355104
weight_decay = 0.00010189105243995853

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 416
dropout = 0.06296897582879268
