seed = 5
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-0-fifa"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0008781718155862455
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 320
dropout = 0.27977752987615717
