seed = 7
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-large-0-year"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0007424074253399561
weight_decay = 0.00023046412101688019

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 5
d_block = 464
dropout = 0.36956277801497434
