seed = 14
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/maps-routing"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.00038809816796862086
weight_decay = 0.008258078192221048

[model]
arch_type = "tabm-mini"
k = 32
share_training_batches = false

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 384
dropout = 0.15581555545875359

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 20

[bins]
n_bins = 9
