seed = 12
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-2-bank-marketing"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0007332038931692587
weight_decay = 0.014430413022687329

[model]
arch_type = "tabm-mini"
k = 32
share_training_batches = false

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 992
dropout = 0.33612902776453624

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 28

[bins]
n_bins = 19
