seed = 6
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-1-credit"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.004067069257107871
weight_decay = 0.00026622553426504283

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 848
dropout = 0.4024511838563605

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 20

[bins]
n_bins = 8
