seed = 5
batch_size = 32
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-1-phoneme"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0035766186527038737
weight_decay = 0.0007620044651406871

[model]
arch_type = "tabm"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 608
dropout = 0.0050539627124579906

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 12

[bins]
n_bins = 112
