seed = 8
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/ecom-offers"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00010075605120306949
weight_decay = 0.0001731775833784439

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 688
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 12

[bins]
n_bins = 33
