seed = 0
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-2-MagicTelescope"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0012191449329314354
weight_decay = 0.09397178311549866

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 448
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 32

[bins]
n_bins = 97
