seed = 4
batch_size = 32
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-3-phoneme"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00233491637827433
weight_decay = 0.000466676768450944

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 832
dropout = 0.053062920207374895

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 32

[bins]
n_bins = 61
