seed = 8
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/churn"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.00043823065744616447
weight_decay = 0.0

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 752
dropout = 0.16056674813716165

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 28

[bins]
n_bins = 9
