seed = 12
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/maps-routing"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0004703285053350615
weight_decay = 0.0

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 832
dropout = 0.44945759980939237

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 12

[bins]
n_bins = 2
