seed = 2
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-0-house_sales"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0001440919622190767
weight_decay = 0.07171885873097458

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 64
dropout = 0.09380381374182956
