seed = 1
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/otto"

[optimizer]
type = "AdamW"
lr = 0.0029765984372315023
weight_decay = 0.00019650475164070602

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 1008
dropout = 0.12415331337383112

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 20

[bins]
n_bins = 50
