seed = 2
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-1-pol"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0003616158719801237
weight_decay = 0.00012861565995794078

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 96
dropout = 0.044036269736458744

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 32

[bins]
n_bins = 105
