seed = 11
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-0-pol"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0016597874855272564
weight_decay = 0.009432041802104284

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 368
dropout = 0.3857550543641392

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 8

[bins]
n_bins = 25
