seed = 5
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/maps-routing"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0006651177618565274
weight_decay = 0.014013491162891908

[model]
arch_type = "tabm"
k = 32
share_training_batches = false

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 480
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 24

[bins]
n_bins = 3
