seed = 11
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-2-kdd_ipums_la_97-small"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0001862986899505689
weight_decay = 0.00018118906109117138

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 864
dropout = 0.2130967789564994

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 12

[bins]
n_bins = 10
