seed = 9
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-cat-large-0-road-safety"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0014163501429175726
weight_decay = 0.0

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 992
dropout = 0.2766285061331004

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 32

[bins]
n_bins = 41
