seed = 0
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-0-Ailerons"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0015919026657451472
weight_decay = 0.0023021372372217853

[model]
arch_type = "tabm"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 864
dropout = 0.2105754364735134

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 16

[bins]
n_bins = 44
