seed = 13
batch_size = 32
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-2-wine"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00017082207069015493
weight_decay = 0.0008760770404306085

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 304
dropout = 0.2969958931531812

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 12

[bins]
n_bins = 54
