seed = 6
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-2-MiamiHousing2016"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00010847589393412247
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 464
dropout = 0.2691897895812724

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 24

[bins]
n_bins = 99
