seed = 12
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-1-MagicTelescope"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0007876307750025987
weight_decay = 0.011493338179823459

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 784
dropout = 0.21942243465861727
