seed = 10
batch_size = 32
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-0-phoneme"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0005633205668635612
weight_decay = 0.0011688692354413614

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 576
dropout = 0.16043181008564397

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 28

[bins]
n_bins = 89
