seed = 0
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/microsoft"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0026524259191408823
weight_decay = 0.002546558192892438

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 640
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 12

[bins]
n_bins = 17
