seed = 9
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-1-elevators"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0004399589403850317
weight_decay = 0.00013691625534998188

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 160
dropout = 0.15718378830523938
