seed = 2
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-cat-medium-0-KDDCup09_upselling"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0003636111435990783
weight_decay = 0.020311934753100273

[model]
arch_type = "tabm"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 544
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 20

[bins]
n_bins = 7
