seed = 3
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-0-superconduct"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0019004437980101394
weight_decay = 0.0006421802679097529

[model]
arch_type = "tabm-mini"
k = 32
share_training_batches = false

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 400
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 24

[bins]
n_bins = 10
