seed = 0
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-2-Mercedes_Benz_Greener_Manufacturing"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0037008671923880565
weight_decay = 0.0

[model]
arch_type = "tabm"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 5
d_block = 416
dropout = 0.13269170810831338
