seed = 2
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-large-0-jannis"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.004157352859011471
weight_decay = 0.0002876199545467971

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 528
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 12

[bins]
n_bins = 9
