seed = 13
batch_size = 128
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-0-cpu_act"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00022096183927597268
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 864
dropout = 0.07102251354471335

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 12

[bins]
n_bins = 48
