seed = 0
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-0-pol"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0004364218060352951
weight_decay = 0.020399074476583814

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 272
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 28

[bins]
n_bins = 111
