seed = 13
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-1-MagicTelescope"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 6.2091209964378e-05
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 5
d_block = 416
dropout = 0.20120792002585808

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 24

[bins]
n_bins = 40
