seed = 8
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/adult"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0023871183334586927
weight_decay = 0.001227542150367235

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 288
dropout = 0.1577486394091434

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 28

[bins]
n_bins = 92
