seed = 12
batch_size = 128
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-1-cpu_act"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0014155695897505396
weight_decay = 0.0

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 480
dropout = 0.11255261605536426

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 8

[bins]
n_bins = 7
