seed = 3
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-large-0-nyc-taxi-green-dec-2016"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0004544764769083791
weight_decay = 0.0

[model]
arch_type = "tabm"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 400
dropout = 0.15344316065109534

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 20

[bins]
n_bins = 111
