seed = 13
batch_size = 128
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-2-isolet"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0005786248422533905
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 544
dropout = 0.14180941058335822
