seed = 1
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/weather"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.003694568815679726
weight_decay = 0.00018570401280072093

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 896
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 8

[bins]
n_bins = 4
