seed = 14
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-0-Brazilian_houses"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0029351680044565893
weight_decay = 0.0

[model]
arch_type = "tabm-packed"
k = 32
share_training_batches = false

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 112
dropout = 0.0
