seed = 0
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-1-analcatdata_supreme"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00010098123176763952
weight_decay = 0.0

[model]
arch_type = "tabm"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 608
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 20

[bins]
n_bins = 55
