seed = 5
batch_size = 128
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-1-cpu_act"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00032971925173373116
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 6
d_block = 480
dropout = 0.18474168971302857
