seed = 13
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/ecom-offers"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00012203371789275253
weight_decay = 0.010232181070101641

[model]
arch_type = "tabm"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 912
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 24

[bins]
n_bins = 33
