seed = 0
batch_size = 128
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-0-isolet"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0006567038802678288
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 352
dropout = 0.1319688599796674

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 8

[bins]
n_bins = 78
