seed = 8
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/cooking-time"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.00010435119163082126
weight_decay = 0.00022293774053705573

[model]
arch_type = "tabm-mini"
k = 32
share_training_batches = false

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 256
dropout = 0.09094683058507791

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 8

[bins]
n_bins = 9
