seed = 2
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-0-analcatdata_supreme"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00024840330741665313
weight_decay = 0.0011051346166803

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 384
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 16

[bins]
n_bins = 12
