seed = 2
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-1-elevators"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.001105758907217311
weight_decay = 0.0

[model]
arch_type = "tabm"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 720
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 24

[bins]
n_bins = 22
