seed = 11
batch_size = 32
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-3-wine"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0003442464465019735
weight_decay = 0.0024667726995190923

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 592
dropout = 0.16946470322749832

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 20

[bins]
n_bins = 15
