seed = 9
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/delivery-eta"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 7.149269185133997e-05
weight_decay = 0.00034255712486350463

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 272
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 20

[bins]
n_bins = 92
