seed = 11
batch_size = 128
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-1-isolet"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0004474356646953312
weight_decay = 0.06481243857292839

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 832
dropout = 0.002668245135427707

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 12

[bins]
n_bins = 24
