seed = 10
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-large-0-year"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.001409201004340121
weight_decay = 0.000326693734663566

[model]
arch_type = "tabm"
k = 32
share_training_batches = false

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 400
dropout = 0.4968036080156015

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 20

[bins]
n_bins = 2
