seed = 10
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/microsoft"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 9.426593177516667e-05
weight_decay = 0.09848442932495301

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 800
dropout = 0.336131726532082
