seed = 12
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/homesite-insurance"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.001330301478738983
weight_decay = 0.000908260907584421

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 496
dropout = 0.28851911925822066

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 24

[bins]
n_bins = 67
