seed = 6
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-large-0-jannis"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0006068512364405656
weight_decay = 0.02407199913679621

[model]
arch_type = "tabm"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 640
dropout = 0.43254223037188716

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 12

[bins]
n_bins = 2
