seed = 5
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-2-Mercedes_Benz_Greener_Manufacturing"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0005040520725679861
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 6
d_block = 224
dropout = 0.04269446743639477
