seed = 5
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-3-Mercedes_Benz_Greener_Manufacturing"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0012225502764498441
weight_decay = 0.0

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 288
dropout = 0.13566931300767598
