seed = 4
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/otto"

[optimizer]
type = "AdamW"
lr = 0.0007171547587744347
weight_decay = 0.030886441861303657

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 864
dropout = 0.43537394590755374

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 20

[bins]
n_bins = 63
