seed = 12
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-0-pol"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.000987081338262192
weight_decay = 0.01831816798944372

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 5
d_block = 784
dropout = 0.0
