seed = 2
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-2-MiamiHousing2016"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00319346281450153
weight_decay = 0.000823227567640741

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 800
dropout = 0.1178928175970065

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 12

[bins]
n_bins = 72
