seed = 10
batch_size = 128
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-0-wine_quality"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.002638624768728511
weight_decay = 0.0

[model]
arch_type = "tabm"
k = 32
share_training_batches = false

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 944
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 24

[bins]
n_bins = 14
