seed = 13
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-large-0-MiniBooNE"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00026099266313791
weight_decay = 0.019897366041434994

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 560
dropout = 0.38594681331216396

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 8

[bins]
n_bins = 13
