seed = 8
batch_size = 128
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-1-wine_quality"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0007403313991293987
weight_decay = 0.006254987962003027

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 912
dropout = 0.298647926310494

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 24

[bins]
n_bins = 45
