seed = 1
batch_size = 32
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-1-phoneme"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0005383742857801525
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 5
d_block = 688
dropout = 0.0
