seed = 13
batch_size = 32
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-0-phoneme"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.003352763881375269
weight_decay = 0.0

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 880
dropout = 0.030296406706836664

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 12

[bins]
n_bins = 101
