seed = 0
function = "bin.model.main"
n_trials = 100

[sampler]
n_startup_trials = 20

[space]
seed = 0
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[space.data]
cache = true
path = "data/regression-num-medium-0-elevators"
num_policy = "noisy-quantile"

[space.optimizer]
type = "AdamW"
lr = [
    "_tune_",
    "loguniform",
    3e-05,
    0.001,
]
weight_decay = [
    "_tune_",
    "?loguniform",
    0.0,
    0.0001,
    0.1,
]

[space.model]
arch_type = "plain"

[space.model.backbone]
type = "MLP"
n_blocks = [
    "_tune_",
    "int",
    1,
    6,
]
d_block = [
    "_tune_",
    "int",
    64,
    1024,
    16,
]
dropout = [
    "_tune_",
    "?uniform",
    0.0,
    0.0,
    0.5,
]
