seed = 9
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-0-house_sales"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0008070149817867732
weight_decay = 0.0

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 272
dropout = 0.10853480592679782

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 32

[bins]
n_bins = 119
