seed = 9
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/adult"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 3.2226814035964625e-05
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 112
dropout = 0.19896995164451625

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 64
d_embedding = 16
frequency_init_scale = 7.953324659578985
lite = false
