seed = 9
batch_size = 32
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-3-wine"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0007434967499148609
weight_decay = 0.0001270799847552423

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 832
dropout = 0.17973231516784327
