seed = 13
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-0-bank-marketing"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0006227452269681419
weight_decay = 0.04653558670196652

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 336
dropout = 0.3802295883600339

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 28

[bins]
n_bins = 123
