seed = 7
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-large-0-year"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00028688680660058686
weight_decay = 0.0002579640930923944

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 5
d_block = 768
dropout = 0.4767450471892426

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 20

[bins]
n_bins = 17
