seed = 2
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-large-0-nyc-taxi-green-dec-2016"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0002726699238570058
weight_decay = 0.002005501913039345

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 240
dropout = 0.2588303575526417

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 20

[bins]
n_bins = 122
