seed = 12
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-0-Mercedes_Benz_Greener_Manufacturing"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 7.946938058067286e-05
weight_decay = 0.00025401287708923405

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 6
d_block = 192
dropout = 0.0
