seed = 3
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-2-Ailerons"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00017669753613511283
weight_decay = 0.00040785928642392727

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 512
dropout = 0.2937378678808271

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 8

[bins]
n_bins = 71
