seed = 11
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-4-Mercedes_Benz_Greener_Manufacturing"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 3.627231301742352e-05
weight_decay = 0.0002495073646709972

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 5
d_block = 96
dropout = 0.24310263283994293
