seed = 2
batch_size = 32
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-4-phoneme"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00035485471896730105
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 560
dropout = 0.14196913194050115

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 24

[bins]
n_bins = 60
