seed = 2
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-large-0-particulate-matter-ukair-2017"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0004284653461189603
weight_decay = 0.00027593103445165565

[model]
arch_type = "tabm-mini"
k = 32
share_training_batches = false

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 976
dropout = 0.252446770108935

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 20

[bins]
n_bins = 55
