seed = 4
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/churn"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0005068237351535733
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 6
d_block = 752
dropout = 0.0
