seed = 10
batch_size = 32
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-3-phoneme"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0008306582622785779
weight_decay = 0.03754734696936558

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 944
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 8

[bins]
n_bins = 91
