seed = 10
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/homecredit-default"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0008832416041848683
weight_decay = 0.04743348238106847

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 720
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 8

[bins]
n_bins = 93
