seed = 10
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-1-Ailerons"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.001781089242269559
weight_decay = 0.06465262211030198

[model]
arch_type = "tabm-packed"
k = 32
share_training_batches = false

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 64
dropout = 0.0
