seed = 2
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-2-MagicTelescope"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0006688299947633692
weight_decay = 0.00017061806098767814

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 784
dropout = 0.46617978889447553

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 12

[bins]
n_bins = 25
