seed = 5
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-0-OnlineNewsPopularity"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 3.015780563219178e-05
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 432
dropout = 0.4727321744615675
