seed = 9
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-0-house_sales"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 9.26896183495068e-05
weight_decay = 0.026761481538023095

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 800
dropout = 0.30599462962196705

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 24

[bins]
n_bins = 118
