seed = 8
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/california"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 3.8853926878343136e-05
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 672
dropout = 0.2608234039902446

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 20

[bins]
n_bins = 108
