seed = 9
batch_size = 128
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-1-isolet"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00158489375646582
weight_decay = 0.0007191413241078845

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 1024
dropout = 0.15177978587726573

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 20

[bins]
n_bins = 24
