seed = 3
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/maps-routing"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 3.0165214881375246e-05
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 992
dropout = 0.4947724194287569
