seed = 11
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-1-Ailerons"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0003395560615313202
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 512
dropout = 0.37242481115996423

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 32

[bins]
n_bins = 31
