seed = 9
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-0-medical_charges"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.000128448219976916
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 5
d_block = 688
dropout = 0.0
