seed = 4
batch_size = 32
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-0-wine"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0008118166286033095
weight_decay = 0.021724644594122582

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 816
dropout = 0.015174160261875196

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 28

[bins]
n_bins = 128
