seed = 1
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/black-friday"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.002063413355362501
weight_decay = 0.007194844305140499

[model]
arch_type = "tabm"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 640
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 16

[bins]
n_bins = 65
