seed = 13
batch_size = 128
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-1-wine_quality"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.003311304840362889
weight_decay = 0.01007803076512397

[model]
arch_type = "tabm"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 944
dropout = 0.05399253006496634

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 20

[bins]
n_bins = 5
