name: tabm
channels:
  - conda-forge
  - nvidia
  - pytorch
  - nodefaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.0.0
  - aiohttp=3.8.6
  - aiosignal=1.3.1
  - alembic=1.12.0
  - anyio=4.0.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.0
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - atk-1.0=2.38.0
  - attrs=23.1.0
  - babel=2.13.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - blas=2.116
  - blas-devel=3.9.0
  - bleach=6.1.0
  - blinker=1.6.3
  - bokeh=3.3.4
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.20.1
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.1
  - cairo=1.18.0
  - catboost=1.2.2
  - category_encoders=2.6.3
  - certifi=2023.7.22
  - cffi=1.16.0
  - charset-normalizer=3.3.0
  - click=8.1.7
  - cmaes=0.10.0
  - colorama=0.4.6
  - colorcet=3.0.1
  - colorlog=6.7.0
  - comm=0.1.4
  - contourpy=1.1.1
  - cryptography=41.0.4
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=11.8
  - cycler=0.12.1
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - einops=0.8.0
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - expat=2.5.0
  - filelock=3.12.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.43.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.4.0
  - gdk-pixbuf=2.42.10
  - gettext=0.21.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - google-auth=2.23.3
  - google-auth-oauthlib=1.0.0
  - graphite2=1.3.13
  - graphviz=8.1.0
  - greenlet=3.0.0
  - grpcio=1.58.1
  - gtk2=2.24.33
  - gts=0.7.6
  - h11=0.14.0
  - h2=4.1.0
  - harfbuzz=8.2.1
  - holoviews=1.18.3
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hvplot=0.10.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.1.0
  - ipykernel=6.25.2
  - ipython=8.16.1
  - ipywidgets=8.1.3
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.2
  - joblib=1.3.2
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.19.1
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.19.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.4.0
  - jupyter_core=5.4.0
  - jupyter_events=0.7.0
  - jupyter_server=2.7.3
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.1.1
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.25.0
  - jupyterlab_widgets=3.0.11
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230802.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.7.2.10
  - libcurand=10.3.3.141
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgd=2.3.3
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.0
  - libgrpc=1.58.1
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnpp=11.8.0.86
  - libnsl=2.0.0
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libprotobuf=4.24.3
  - librsvg=2.56.3
  - libsodium=1.0.18
  - libsqlite=3.43.2
  - libstdcxx-ng=13.2.0
  - libtiff=4.6.0
  - libtool=2.4.7
  - libuuid=2.38.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.11.5
  - libzlib=1.2.13
  - lightgbm=4.0.0
  - linkify-it-py=2.0.0
  - llvm-openmp=17.0.2
  - loguru=0.7.2
  - mako=1.2.4
  - markdown=3.5.2
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mdit-py-plugins=0.4.0
  - mdurl=0.1.0
  - mistune=3.0.1
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - multidict=6.0.4
  - munkres=1.1.4
  - mypy=1.7.1
  - mypy_extensions=1.0.0
  - nbclient=0.8.0
  - nbconvert-core=7.9.2
  - nbformat=5.9.2
  - nccl=2.19.3.1
  - ncurses=6.4.20240210
  - nest-asyncio=1.5.8
  - networkx=3.1
  - notebook-shim=0.2.3
  - numpy=1.26.3
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openssl=3.1.3
  - optuna=3.3.0
  - overrides=7.4.0
  - packaging=23.2
  - pandas=2.1.1
  - pandocfilters=1.5.0
  - panel=1.3.6
  - pango=1.50.14
  - param=2.0.1
  - parso=0.8.3
  - patsy=0.5.5
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3.1
  - pixman=0.42.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.11.0
  - plotly=5.17.0
  - polars=1.5.0
  - prometheus_client=0.17.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - protobuf=4.24.3
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.5.0
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pygments=2.16.1
  - pyjwt=2.8.0
  - pyopenssl=23.2.0
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - python=3.10.12
  - python-dateutil=2.8.2
  - python-dotenv=1.0.1
  - python-fastjsonschema=2.18.1
  - python-graphviz=0.20.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytorch::pytorch=2.0.1
  - pytorch::pytorch-cuda=11.8
  - pytorch::pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pyu2f=0.1.5
  - pyviz_comms=3.0.0
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - re2=2023.03.02
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - rsa=4.9
  - ruff=0.6.0
  - scikit-learn=1.3.1
  - scipy=1.11.3
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlalchemy=2.0.21
  - stack_data=0.6.2
  - statsmodels=0.14.1
  - sympy=1.12.1
  - tbb=2021.10.0
  - tenacity=8.2.3
  - tensorboard=2.15.2
  - tensorboard-data-server=0.7.0
  - terminado=0.17.1
  - threadpoolctl=3.2.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - tomli=2.0.1
  - tomli-w=1.0.0
  - torchtriton=2.0.0
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.11.2
  - types-python-dateutil=2.8.19.14
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - typing_utils=0.1.0
  - tzdata=2023c
  - uc-micro-py=1.0.1
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.0.6
  - wcwidth=0.2.8
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.6.4
  - werkzeug=3.0.0
  - wheel=0.41.2
  - widgetsnbextension=4.0.11
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2023.10.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.2
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - -i https://pypi.org/simple
      - delu==0.0.25
      - rtdl_num_embeddings==0.0.11
      - rtdl_revisiting_models==0.0.2
