seed = 8
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-0-medical_charges"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0004177418728764842
weight_decay = 0.0020060142099021126

[model]
arch_type = "tabm"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 1
d_block = 1008
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 8

[bins]
n_bins = 2
