seed = 8
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-1-elevators"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 7.085207085795521e-05
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 496
dropout = 0.08051628459424368

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 16

[bins]
n_bins = 38
