seed = 3
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-1-kdd_ipums_la_97-small"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00022336597624830748
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 5
d_block = 384
dropout = 0.22197209297140907
