seed = 10
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/higgs-small"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00040919910909576287
weight_decay = 0.07216635702812191

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 592
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 8

[bins]
n_bins = 43
