seed = 14
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-0-OnlineNewsPopularity"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0023797300220446886
weight_decay = 0.0267514697542703

[model]
arch_type = "tabm"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 3
d_block = 960
dropout = 0.2973213186657744

[model.num_embeddings]
type = "PiecewiseLinearEmbeddingsV2"
d_embedding = 20

[bins]
n_bins = 34
